language: python
cache: pip
sudo: false
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
install:
- pip install -r requirements.txt
- travis_wait pip install -r recommended_requirements.txt
- pip install coveralls
- pip install 'coverage<4'
script:
- coverage run --source=pycalc -p ./run_tests
after_success:
- coverage combine
- coverage report -m
- coveralls --verbose
deploy:
  provider: pypi
  # server: https://testpypi.python.org/pypi
  user: duerrp
  skip_cleanup: true
  password:
    secure: C6KG3dFhwueZlI43xYy1Gt/f8rzoZOlrzm2ICojI9pAY4jB6afdbZGbusZMuxiD1O/36m7aWwbZ8yYeiWPkgfV5W6NqTJ7tqsq2lhQYBdtAdFHn2CnwruKfnKeiwggrlUNR5CkKm+S9xKtzanfVonPZD64ZLQXBjUCPl3jH1ZLY=
  on:
    tags: true
    repo: duerrp/pycalc
    branch: master
    python: 3.4